version: "3"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - ./app:/app
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db